package cinema;

public enum ReturnCode {
    OK,
    NO_ACCESS,
    INCORRECT_CINEMA_INDEX,
    INCORRECT_HALL_INDEX,
    INCORRECT_ROW_INDEX,
    INCORRECT_SCREENING_INDEX,
    NOT_ENOUGH_FREE_SEATS,
    NO_CLOSEST_SCREENINGS,
    SCREENING_OVERLAP
}
